/**
 * ConsumerGrantGrantIdPath automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.consumer;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class ConsumerGrantGrantIdPath {
    private String grantId;
    @JsonSetter("grant_id")
    public void setGrantId(String grantId) {
        this.grantId = grantId;
    }
    @JsonGetter("grant_id")
    public String getGrantId() {
        return this.grantId;
    }
}
