/**
 * ConsumerPageGroup automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.consumer;

import app.sdkgen.client.ResourceAbstract;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.http.client.HttpClient;

public class ConsumerPageGroup extends ResourceAbstract {
    public ConsumerPageGroup(String baseUrl, HttpClient httpClient, ObjectMapper objectMapper) {
        super(baseUrl, httpClient, objectMapper);
    }

    /**
     * Endpoint: /consumer/page/:page_id
     */
    public ConsumerPageByPageIdResource getConsumerPageByPageId(String page_id) {
        return new ConsumerPageByPageIdResource(
            page_id,
            this.baseUrl,
            this.httpClient
        );
    }

    /**
     * Endpoint: /consumer/page
     */
    public ConsumerPageResource getConsumerPage() {
        return new ConsumerPageResource(
            this.baseUrl,
            this.httpClient
        );
    }

}
