/**
 * ConsumerPaymentGroup automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.consumer;

import app.sdkgen.client.ResourceAbstract;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.http.client.HttpClient;

public class ConsumerPaymentGroup extends ResourceAbstract {
    public ConsumerPaymentGroup(String baseUrl, HttpClient httpClient, ObjectMapper objectMapper) {
        super(baseUrl, httpClient, objectMapper);
    }

    /**
     * Endpoint: /consumer/payment/:provider/checkout
     */
    public ConsumerPaymentByProviderCheckoutResource getConsumerPaymentByProviderCheckout(String provider) {
        return new ConsumerPaymentByProviderCheckoutResource(
            provider,
            this.baseUrl,
            this.httpClient
        );
    }

    /**
     * Endpoint: /consumer/payment/:provider/portal
     */
    public ConsumerPaymentByProviderPortalResource getConsumerPaymentByProviderPortal(String provider) {
        return new ConsumerPaymentByProviderPortalResource(
            provider,
            this.baseUrl,
            this.httpClient
        );
    }

}
