/**
 * EventSubscription automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.consumer;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class EventSubscription {
    private int id;
    private int status;
    private String event;
    private String endpoint;
    private EventSubscriptionResponse[] responses;
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }
    @JsonGetter("id")
    public int getId() {
        return this.id;
    }
    @JsonSetter("status")
    public void setStatus(int status) {
        this.status = status;
    }
    @JsonGetter("status")
    public int getStatus() {
        return this.status;
    }
    @JsonSetter("event")
    public void setEvent(String event) {
        this.event = event;
    }
    @JsonGetter("event")
    public String getEvent() {
        return this.event;
    }
    @JsonSetter("endpoint")
    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }
    @JsonGetter("endpoint")
    public String getEndpoint() {
        return this.endpoint;
    }
    @JsonSetter("responses")
    public void setResponses(EventSubscriptionResponse[] responses) {
        this.responses = responses;
    }
    @JsonGetter("responses")
    public EventSubscriptionResponse[] getResponses() {
        return this.responses;
    }
}
