/**
 * Transaction automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.consumer;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class Transaction {
    private int id;
    private int status;
    private String transactionId;
    private float amount;
    private int updateDate;
    private int insertDate;
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }
    @JsonGetter("id")
    public int getId() {
        return this.id;
    }
    @JsonSetter("status")
    public void setStatus(int status) {
        this.status = status;
    }
    @JsonGetter("status")
    public int getStatus() {
        return this.status;
    }
    @JsonSetter("transactionId")
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }
    @JsonGetter("transactionId")
    public String getTransactionId() {
        return this.transactionId;
    }
    @JsonSetter("amount")
    public void setAmount(float amount) {
        this.amount = amount;
    }
    @JsonGetter("amount")
    public float getAmount() {
        return this.amount;
    }
    @JsonSetter("updateDate")
    public void setUpdateDate(int updateDate) {
        this.updateDate = updateDate;
    }
    @JsonGetter("updateDate")
    public int getUpdateDate() {
        return this.updateDate;
    }
    @JsonSetter("insertDate")
    public void setInsertDate(int insertDate) {
        this.insertDate = insertDate;
    }
    @JsonGetter("insertDate")
    public int getInsertDate() {
        return this.insertDate;
    }
}
