/**
 * UserRefresh automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.consumer;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class UserRefresh {
    private String refreshToken;
    @JsonSetter("refresh_token")
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }
    @JsonGetter("refresh_token")
    public String getRefreshToken() {
        return this.refreshToken;
    }
}
