/**
 * UserAccount automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.consumer;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.time.LocalDateTime;
public class UserAccount {
    private int id;
    private int planId;
    private int status;
    private String name;
    private String email;
    private int points;
    private String[] scopes;
    private UserAttributes attributes;
    private LocalDateTime date;
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }
    @JsonGetter("id")
    public int getId() {
        return this.id;
    }
    @JsonSetter("planId")
    public void setPlanId(int planId) {
        this.planId = planId;
    }
    @JsonGetter("planId")
    public int getPlanId() {
        return this.planId;
    }
    @JsonSetter("status")
    public void setStatus(int status) {
        this.status = status;
    }
    @JsonGetter("status")
    public int getStatus() {
        return this.status;
    }
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }
    @JsonGetter("name")
    public String getName() {
        return this.name;
    }
    @JsonSetter("email")
    public void setEmail(String email) {
        this.email = email;
    }
    @JsonGetter("email")
    public String getEmail() {
        return this.email;
    }
    @JsonSetter("points")
    public void setPoints(int points) {
        this.points = points;
    }
    @JsonGetter("points")
    public int getPoints() {
        return this.points;
    }
    @JsonSetter("scopes")
    public void setScopes(String[] scopes) {
        this.scopes = scopes;
    }
    @JsonGetter("scopes")
    public String[] getScopes() {
        return this.scopes;
    }
    @JsonSetter("attributes")
    public void setAttributes(UserAttributes attributes) {
        this.attributes = attributes;
    }
    @JsonGetter("attributes")
    public UserAttributes getAttributes() {
        return this.attributes;
    }
    @JsonSetter("date")
    public void setDate(LocalDateTime date) {
        this.date = date;
    }
    @JsonGetter("date")
    public LocalDateTime getDate() {
        return this.date;
    }
}
