/**
 * AgentOutput automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("This object represents an agent output")
public class AgentOutput {
    @JsonPropertyDescription("Chat id of this conversation")
    @JsonProperty("id")
    private String id;

    @JsonProperty("item")
    private AgentItem item;


    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return this.id;
    }

    public void setItem(AgentItem item) {
        this.item = item;
    }

    public AgentItem getItem() {
        return this.item;
    }
}

