/**
 * AgentInput automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("This object represents an agent input")
public class AgentInput {
    @JsonPropertyDescription("Optional the chat id of this conversation")
    @JsonProperty("previousId")
    private String previousId;

    @JsonProperty("item")
    private AgentItem item;


    public void setPreviousId(String previousId) {
        this.previousId = previousId;
    }

    public String getPreviousId() {
        return this.previousId;
    }

    public void setItem(AgentItem item) {
        this.item = item;
    }

    public AgentItem getItem() {
        return this.item;
    }
}

