/**
 * BackendAgentRequest automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("This object represents an agent request")
public class BackendAgentRequest {
    @JsonPropertyDescription("The intent of this request i.e. to develop an action or a general request")
    private String intent;
    @JsonPropertyDescription("The input message")
    private BackendAgentMessage input;

    @JsonSetter("intent")
    public void setIntent(String intent) {
        this.intent = intent;
    }

    @JsonGetter("intent")
    public String getIntent() {
        return this.intent;
    }

    @JsonSetter("input")
    public void setInput(BackendAgentMessage input) {
        this.input = input;
    }

    @JsonGetter("input")
    public BackendAgentMessage getInput() {
        return this.input;
    }
}

