/**
 * BackendLogError automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

public class BackendLogError {
    @JsonPropertyDescription("Unique identifier for the object")
    @JsonProperty("id")
    private Integer id;

    @JsonProperty("logId")
    private Integer logId;

    @JsonProperty("message")
    private String message;

    @JsonProperty("trace")
    private String trace;

    @JsonProperty("file")
    private String file;

    @JsonProperty("line")
    private Integer line;

    @JsonProperty("insertDate")
    private java.time.LocalDateTime insertDate;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    public Integer getLogId() {
        return this.logId;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getMessage() {
        return this.message;
    }

    public void setTrace(String trace) {
        this.trace = trace;
    }

    public String getTrace() {
        return this.trace;
    }

    public void setFile(String file) {
        this.file = file;
    }

    public String getFile() {
        return this.file;
    }

    public void setLine(Integer line) {
        this.line = line;
    }

    public Integer getLine() {
        return this.line;
    }

    public void setInsertDate(java.time.LocalDateTime insertDate) {
        this.insertDate = insertDate;
    }

    public java.time.LocalDateTime getInsertDate() {
        return this.insertDate;
    }
}

