/**
 * BackendGeneratorIndexProviders automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class BackendGeneratorIndexProviders {
    private List<BackendGeneratorIndexProvider> providers;
    @JsonSetter("providers")
    public void setProviders(List<BackendGeneratorIndexProvider> providers) {
        this.providers = providers;
    }
    @JsonGetter("providers")
    public List<BackendGeneratorIndexProvider> getProviders() {
        return this.providers;
    }
}
