/**
 * BackendRate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class BackendRate {
    private Integer id;
    private Integer priority;
    private String name;
    private Integer rateLimit;
    private String timespan;
    private java.util.List<BackendRateAllocation> allocation;
    private CommonMetadata metadata;

    @JsonSetter("id")
    public void setId(Integer id) {
        this.id = id;
    }

    @JsonGetter("id")
    public Integer getId() {
        return this.id;
    }

    @JsonSetter("priority")
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    @JsonGetter("priority")
    public Integer getPriority() {
        return this.priority;
    }

    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    @JsonGetter("name")
    public String getName() {
        return this.name;
    }

    @JsonSetter("rateLimit")
    public void setRateLimit(Integer rateLimit) {
        this.rateLimit = rateLimit;
    }

    @JsonGetter("rateLimit")
    public Integer getRateLimit() {
        return this.rateLimit;
    }

    @JsonSetter("timespan")
    public void setTimespan(String timespan) {
        this.timespan = timespan;
    }

    @JsonGetter("timespan")
    public String getTimespan() {
        return this.timespan;
    }

    @JsonSetter("allocation")
    public void setAllocation(java.util.List<BackendRateAllocation> allocation) {
        this.allocation = allocation;
    }

    @JsonGetter("allocation")
    public java.util.List<BackendRateAllocation> getAllocation() {
        return this.allocation;
    }

    @JsonSetter("metadata")
    public void setMetadata(CommonMetadata metadata) {
        this.metadata = metadata;
    }

    @JsonGetter("metadata")
    public CommonMetadata getMetadata() {
        return this.metadata;
    }
}

