/**
 * BackendSchemaForm automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

/**
 * Contains a UI vocabulary to describe the UI of the schema
 */
public class BackendSchemaForm extends java.util.HashMap<String, Object> {
}

