/**
 * BackendStatisticChartSeries automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

public class BackendStatisticChartSeries {
    private String name;
    private java.util.List<Double> data;

    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    @JsonGetter("name")
    public String getName() {
        return this.name;
    }

    @JsonSetter("data")
    public void setData(java.util.List<Double> data) {
        this.data = data;
    }

    @JsonGetter("data")
    public java.util.List<Double> getData() {
        return this.data;
    }
}

