/**
 * BackendAppCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("A paginated collection of app objects")
public class BackendAppCollection extends CommonCollection<BackendApp> {
}

