/**
 * BackendRateAllocation automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("This object represents a rate allocation, in case a request matches it gets assigned to the attached rate")
public class BackendRateAllocation {
    @JsonPropertyDescription("Unique identifier for the object")
    @JsonProperty("id")
    private Integer id;

    @JsonProperty("operationId")
    private Integer operationId;

    @JsonProperty("userId")
    private Integer userId;

    @JsonProperty("planId")
    private Integer planId;

    @JsonProperty("appId")
    private Integer appId;

    @JsonPropertyDescription("Whether the request is authenticated")
    @JsonProperty("authenticated")
    private Boolean authenticated;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setOperationId(Integer operationId) {
        this.operationId = operationId;
    }

    public Integer getOperationId() {
        return this.operationId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    public Integer getPlanId() {
        return this.planId;
    }

    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    public Integer getAppId() {
        return this.appId;
    }

    public void setAuthenticated(Boolean authenticated) {
        this.authenticated = authenticated;
    }

    public Boolean getAuthenticated() {
        return this.authenticated;
    }
}

