/**
 * BackendEvent automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("This object represents an event which can be triggered by an action")
public class BackendEvent {
    @JsonPropertyDescription("Unique identifier for the object")
    @JsonProperty("id")
    private Integer id;

    @JsonPropertyDescription("Unique name of the object")
    @JsonProperty("name")
    private String name;

    @JsonProperty("description")
    private String description;

    @JsonProperty("schema")
    private String schema;

    @JsonPropertyDescription("Use this parameter to attach key-value data")
    @JsonProperty("metadata")
    private CommonMetadata metadata;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return this.description;
    }

    public void setSchema(String schema) {
        this.schema = schema;
    }

    public String getSchema() {
        return this.schema;
    }

    public void setMetadata(CommonMetadata metadata) {
        this.metadata = metadata;
    }

    public CommonMetadata getMetadata() {
        return this.metadata;
    }
}

