/**
 * BackendTrashTypes automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

public class BackendTrashTypes {
    @JsonProperty("types")
    private java.util.List<String> types;


    public void setTypes(java.util.List<String> types) {
        this.types = types;
    }

    public java.util.List<String> getTypes() {
        return this.types;
    }
}

