/**
 * BackendActionIndex automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class BackendActionIndex {
    private List<BackendActionIndexEntry> actions;
    @JsonSetter("actions")
    public void setActions(List<BackendActionIndexEntry> actions) {
        this.actions = actions;
    }
    @JsonGetter("actions")
    public List<BackendActionIndexEntry> getActions() {
        return this.actions;
    }
}
