/**
 * BackendBackupImportResult automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Result of a backup import operation")
public class BackendBackupImportResult {
    @JsonProperty("success")
    private Boolean success;

    @JsonProperty("message")
    private String message;

    @JsonProperty("logs")
    private java.util.List<String> logs;


    public void setSuccess(Boolean success) {
        this.success = success;
    }

    public Boolean getSuccess() {
        return this.success;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getMessage() {
        return this.message;
    }

    public void setLogs(java.util.List<String> logs) {
        this.logs = logs;
    }

    public java.util.List<String> getLogs() {
        return this.logs;
    }
}

