/**
 * BackendPage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("This object represents a page at the developer portal")
public class BackendPage {
    @JsonPropertyDescription("Unique identifier for the object")
    @JsonProperty("id")
    private Integer id;

    @JsonPropertyDescription("Status of the object either 1 = visible, 2 = invisible or 0 = deleted")
    @JsonProperty("status")
    private Integer status;

    @JsonPropertyDescription("Title of the page")
    @JsonProperty("title")
    private String title;

    @JsonPropertyDescription("Slug of the page which gets dynamically generated from the title")
    @JsonProperty("slug")
    private String slug;

    @JsonPropertyDescription("HTML content of this page")
    @JsonProperty("content")
    private String content;

    @JsonPropertyDescription("Use this parameter to attach key-value data")
    @JsonProperty("metadata")
    private CommonMetadata metadata;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitle() {
        return this.title;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getSlug() {
        return this.slug;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getContent() {
        return this.content;
    }

    public void setMetadata(CommonMetadata metadata) {
        this.metadata = metadata;
    }

    public CommonMetadata getMetadata() {
        return this.metadata;
    }
}

