/**
 * BackendConnectionIndex automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Contains all possible classes which can be used at an connection as class")
public class BackendConnectionIndex {
    private java.util.List<BackendConnectionIndexEntry> connections;

    @JsonSetter("connections")
    public void setConnections(java.util.List<BackendConnectionIndexEntry> connections) {
        this.connections = connections;
    }

    @JsonGetter("connections")
    public java.util.List<BackendConnectionIndexEntry> getConnections() {
        return this.connections;
    }
}

