/**
 * BackendActionExecuteResponseHeaders automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

public class BackendActionExecuteResponseHeaders extends java.util.HashMap<String, String> {
}

