/**
 * BackendScopeCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("A paginated collection of scope objects")
public class BackendScopeCollection extends CommonCollection<BackendScope> {
}

