/**
 * BackendAccountChangePassword automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

public class BackendAccountChangePassword {
    @JsonPropertyDescription("The old password")
    private String oldPassword;
    @JsonPropertyDescription("The new password")
    private String newPassword;
    @JsonPropertyDescription("To verify the new password must contain the same value as the new password")
    private String verifyPassword;

    @JsonSetter("oldPassword")
    public void setOldPassword(String oldPassword) {
        this.oldPassword = oldPassword;
    }

    @JsonGetter("oldPassword")
    public String getOldPassword() {
        return this.oldPassword;
    }

    @JsonSetter("newPassword")
    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }

    @JsonGetter("newPassword")
    public String getNewPassword() {
        return this.newPassword;
    }

    @JsonSetter("verifyPassword")
    public void setVerifyPassword(String verifyPassword) {
        this.verifyPassword = verifyPassword;
    }

    @JsonGetter("verifyPassword")
    public String getVerifyPassword() {
        return this.verifyPassword;
    }
}

