/**
 * BackendGeneratorProviderChangelog automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

public class BackendGeneratorProviderChangelog {
    @JsonProperty("schemas")
    private java.util.List<BackendSchema> schemas;

    @JsonProperty("actions")
    private java.util.List<BackendAction> actions;

    @JsonProperty("operations")
    private java.util.List<BackendOperation> operations;


    public void setSchemas(java.util.List<BackendSchema> schemas) {
        this.schemas = schemas;
    }

    public java.util.List<BackendSchema> getSchemas() {
        return this.schemas;
    }

    public void setActions(java.util.List<BackendAction> actions) {
        this.actions = actions;
    }

    public java.util.List<BackendAction> getActions() {
        return this.actions;
    }

    public void setOperations(java.util.List<BackendOperation> operations) {
        this.operations = operations;
    }

    public java.util.List<BackendOperation> getOperations() {
        return this.operations;
    }
}

