/**
 * BackendBundle automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("This object represents a bundle which contains action, schema, event, cronjob and trigger configurations from you local instance")
public class BackendBundle {
    @JsonPropertyDescription("Unique identifier for the object")
    @JsonProperty("id")
    private Integer id;

    @JsonPropertyDescription("Unique name of the object")
    @JsonProperty("name")
    private String name;

    @JsonPropertyDescription("Version of this bundle")
    @JsonProperty("version")
    private String version;

    @JsonPropertyDescription("Icon to represent this bundle")
    @JsonProperty("icon")
    private String icon;

    @JsonPropertyDescription("Short summary which explains the use case for this bundle")
    @JsonProperty("summary")
    private String summary;

    @JsonPropertyDescription("Long description how to use this bundle may also contains markdown syntax")
    @JsonProperty("description")
    private String description;

    @JsonPropertyDescription("Optional a cost for this bundle")
    @JsonProperty("cost")
    private Integer cost;

    @JsonPropertyDescription("The bundle configuration")
    @JsonProperty("config")
    private BackendBundleConfig config;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getVersion() {
        return this.version;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getIcon() {
        return this.icon;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getSummary() {
        return this.summary;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return this.description;
    }

    public void setCost(Integer cost) {
        this.cost = cost;
    }

    public Integer getCost() {
        return this.cost;
    }

    public void setConfig(BackendBundleConfig config) {
        this.config = config;
    }

    public BackendBundleConfig getConfig() {
        return this.config;
    }
}

