/**
 * BackendSchemaSource automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

/**
 * Contains the TypeSchema specification
 */
public class BackendSchemaSource extends java.util.HashMap<String, Object> {
}

