/**
 * BackendActionIndexEntry automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Represents a concrete action class")
public class BackendActionIndexEntry {
    @JsonPropertyDescription("Human-readable name of the action class")
    @JsonProperty("name")
    private String name;

    @JsonPropertyDescription("Technical identifier of the action class")
    @JsonProperty("class")
    private String _class;


    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setClass(String _class) {
        this._class = _class;
    }

    public String get_Class() {
        return this._class;
    }
}

