/**
 * BackendDatabaseTableForeignKeyConstraint automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("This object represents a foreign key constraint on a relational database")
public class BackendDatabaseTableForeignKeyConstraint {
    @JsonPropertyDescription("Name of the foreign key constraint")
    @JsonProperty("name")
    private String name;

    @JsonPropertyDescription("Name of the foreign table")
    @JsonProperty("foreignTable")
    private String foreignTable;

    @JsonPropertyDescription("Local column names")
    @JsonProperty("localColumnNames")
    private java.util.List<String> localColumnNames;

    @JsonPropertyDescription("Foreign column names")
    @JsonProperty("foreignColumnNames")
    private java.util.List<String> foreignColumnNames;


    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setForeignTable(String foreignTable) {
        this.foreignTable = foreignTable;
    }

    public String getForeignTable() {
        return this.foreignTable;
    }

    public void setLocalColumnNames(java.util.List<String> localColumnNames) {
        this.localColumnNames = localColumnNames;
    }

    public java.util.List<String> getLocalColumnNames() {
        return this.localColumnNames;
    }

    public void setForeignColumnNames(java.util.List<String> foreignColumnNames) {
        this.foreignColumnNames = foreignColumnNames;
    }

    public java.util.List<String> getForeignColumnNames() {
        return this.foreignColumnNames;
    }
}

