/**
 * BackendConnectionRedirectResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Redirect response to initiate an OAuth2 flow")
public class BackendConnectionRedirectResponse {
    @JsonPropertyDescription("Target URI to redirect the user for OAuth2 authentication")
    @JsonProperty("redirectUri")
    private String redirectUri;


    public void setRedirectUri(String redirectUri) {
        this.redirectUri = redirectUri;
    }

    public String getRedirectUri() {
        return this.redirectUri;
    }
}

