/**
 * BackendDashboard automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class BackendDashboard {
    private BackendStatisticChart errorsPerOperation;
    private BackendStatisticChart incomingRequests;
    private BackendStatisticChart incomingTransactions;
    private BackendStatisticChart mostUsedOperations;
    private BackendStatisticChart timePerOperation;
    private BackendDashboardApps latestApps;
    private BackendDashboardRequests latestRequests;
    private BackendDashboardUsers latestUsers;
    private BackendDashboardTransactions latestTransactions;
    @JsonSetter("errorsPerOperation")
    public void setErrorsPerOperation(BackendStatisticChart errorsPerOperation) {
        this.errorsPerOperation = errorsPerOperation;
    }
    @JsonGetter("errorsPerOperation")
    public BackendStatisticChart getErrorsPerOperation() {
        return this.errorsPerOperation;
    }
    @JsonSetter("incomingRequests")
    public void setIncomingRequests(BackendStatisticChart incomingRequests) {
        this.incomingRequests = incomingRequests;
    }
    @JsonGetter("incomingRequests")
    public BackendStatisticChart getIncomingRequests() {
        return this.incomingRequests;
    }
    @JsonSetter("incomingTransactions")
    public void setIncomingTransactions(BackendStatisticChart incomingTransactions) {
        this.incomingTransactions = incomingTransactions;
    }
    @JsonGetter("incomingTransactions")
    public BackendStatisticChart getIncomingTransactions() {
        return this.incomingTransactions;
    }
    @JsonSetter("mostUsedOperations")
    public void setMostUsedOperations(BackendStatisticChart mostUsedOperations) {
        this.mostUsedOperations = mostUsedOperations;
    }
    @JsonGetter("mostUsedOperations")
    public BackendStatisticChart getMostUsedOperations() {
        return this.mostUsedOperations;
    }
    @JsonSetter("timePerOperation")
    public void setTimePerOperation(BackendStatisticChart timePerOperation) {
        this.timePerOperation = timePerOperation;
    }
    @JsonGetter("timePerOperation")
    public BackendStatisticChart getTimePerOperation() {
        return this.timePerOperation;
    }
    @JsonSetter("latestApps")
    public void setLatestApps(BackendDashboardApps latestApps) {
        this.latestApps = latestApps;
    }
    @JsonGetter("latestApps")
    public BackendDashboardApps getLatestApps() {
        return this.latestApps;
    }
    @JsonSetter("latestRequests")
    public void setLatestRequests(BackendDashboardRequests latestRequests) {
        this.latestRequests = latestRequests;
    }
    @JsonGetter("latestRequests")
    public BackendDashboardRequests getLatestRequests() {
        return this.latestRequests;
    }
    @JsonSetter("latestUsers")
    public void setLatestUsers(BackendDashboardUsers latestUsers) {
        this.latestUsers = latestUsers;
    }
    @JsonGetter("latestUsers")
    public BackendDashboardUsers getLatestUsers() {
        return this.latestUsers;
    }
    @JsonSetter("latestTransactions")
    public void setLatestTransactions(BackendDashboardTransactions latestTransactions) {
        this.latestTransactions = latestTransactions;
    }
    @JsonGetter("latestTransactions")
    public BackendDashboardTransactions getLatestTransactions() {
        return this.latestTransactions;
    }
}
