/**
 * BackendMarketplaceCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class BackendMarketplaceCollection {
    private BackendMarketplaceCollectionApps apps;
    @JsonSetter("apps")
    public void setApps(BackendMarketplaceCollectionApps apps) {
        this.apps = apps;
    }
    @JsonGetter("apps")
    public BackendMarketplaceCollectionApps getApps() {
        return this.apps;
    }
}
