/**
 * BackendLogCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("A paginated collection of log objects")
public class BackendLogCollection extends CommonCollection<BackendLog> {
}

