/**
 * BackendLogError automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

public class BackendLogError {
    @JsonPropertyDescription("Unique identifier for the object")
    private Integer id;
    private Integer logId;
    private String message;
    private String trace;
    private String file;
    private Integer line;
    private java.time.LocalDateTime insertDate;

    @JsonSetter("id")
    public void setId(Integer id) {
        this.id = id;
    }

    @JsonGetter("id")
    public Integer getId() {
        return this.id;
    }

    @JsonSetter("logId")
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    @JsonGetter("logId")
    public Integer getLogId() {
        return this.logId;
    }

    @JsonSetter("message")
    public void setMessage(String message) {
        this.message = message;
    }

    @JsonGetter("message")
    public String getMessage() {
        return this.message;
    }

    @JsonSetter("trace")
    public void setTrace(String trace) {
        this.trace = trace;
    }

    @JsonGetter("trace")
    public String getTrace() {
        return this.trace;
    }

    @JsonSetter("file")
    public void setFile(String file) {
        this.file = file;
    }

    @JsonGetter("file")
    public String getFile() {
        return this.file;
    }

    @JsonSetter("line")
    public void setLine(Integer line) {
        this.line = line;
    }

    @JsonGetter("line")
    public Integer getLine() {
        return this.line;
    }

    @JsonSetter("insertDate")
    public void setInsertDate(java.time.LocalDateTime insertDate) {
        this.insertDate = insertDate;
    }

    @JsonGetter("insertDate")
    public java.time.LocalDateTime getInsertDate() {
        return this.insertDate;
    }
}

