/**
 * BackendAgentUpdate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Payload for updating an existing AI agent")
public class BackendAgentUpdate extends BackendAgent {
}

