/**
 * BackendAgentContentChoice automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Choice agent message")
public class BackendAgentContentChoice extends BackendAgentContent {
    @JsonPropertyDescription("Contains multiple agent messages")
    private java.util.List<BackendAgentContent> items;

    @JsonSetter("items")
    public void setItems(java.util.List<BackendAgentContent> items) {
        this.items = items;
    }

    @JsonGetter("items")
    public java.util.List<BackendAgentContent> getItems() {
        return this.items;
    }
}

