/**
 * BackendMarketplaceRemoteApp automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class BackendMarketplaceRemoteApp extends BackendMarketplaceApp {
    private BackendMarketplaceApp local;
    @JsonSetter("local")
    public void setLocal(BackendMarketplaceApp local) {
        this.local = local;
    }
    @JsonGetter("local")
    public BackendMarketplaceApp getLocal() {
        return this.local;
    }
}
