/**
 * BackendDatabaseTableIndex automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class BackendDatabaseTableIndex {
    private String name;
    private Boolean unique;
    private List<String> columns;
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }
    @JsonGetter("name")
    public String getName() {
        return this.name;
    }
    @JsonSetter("unique")
    public void setUnique(Boolean unique) {
        this.unique = unique;
    }
    @JsonGetter("unique")
    public Boolean getUnique() {
        return this.unique;
    }
    @JsonSetter("columns")
    public void setColumns(List<String> columns) {
        this.columns = columns;
    }
    @JsonGetter("columns")
    public List<String> getColumns() {
        return this.columns;
    }
}
