/**
 * BackendSdkResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class BackendSdkResponse {
    private BackendSdkTypes types;
    @JsonSetter("types")
    public void setTypes(BackendSdkTypes types) {
        this.types = types;
    }
    @JsonGetter("types")
    public BackendSdkTypes getTypes() {
        return this.types;
    }
}
