/**
 * BackendAgentContentToolCall automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Tool call agent message")
public class BackendAgentContentToolCall extends BackendAgentContent {
    @JsonPropertyDescription("An array of concrete functions")
    private java.util.List<BackendAgentContentToolCallFunction> functions;

    @JsonSetter("functions")
    public void setFunctions(java.util.List<BackendAgentContentToolCallFunction> functions) {
        this.functions = functions;
    }

    @JsonGetter("functions")
    public java.util.List<BackendAgentContentToolCallFunction> getFunctions() {
        return this.functions;
    }
}

