/**
 * BackendSdkGenerate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Payload defining target format and configuration for triggering an SDK generation run")
public class BackendSdkGenerate {
    @JsonPropertyDescription("Target language format or output type for the SDK build")
    @JsonProperty("format")
    private String format;

    @JsonPropertyDescription("Optional generator specific configuration options")
    @JsonProperty("config")
    private String config;


    public void setFormat(String format) {
        this.format = format;
    }

    public String getFormat() {
        return this.format;
    }

    public void setConfig(String config) {
        this.config = config;
    }

    public String getConfig() {
        return this.config;
    }
}

