/**
 * BackendDashboard automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Represents an object containing all widget data for the dashboard")
public class BackendDashboard {
    @JsonProperty("errorsPerOperation")
    private BackendStatisticChart errorsPerOperation;

    @JsonProperty("incomingRequests")
    private BackendStatisticChart incomingRequests;

    @JsonProperty("incomingTransactions")
    private BackendStatisticChart incomingTransactions;

    @JsonProperty("mostUsedOperations")
    private BackendStatisticChart mostUsedOperations;

    @JsonProperty("timePerOperation")
    private BackendStatisticChart timePerOperation;

    @JsonProperty("testCoverage")
    private BackendStatisticChart testCoverage;

    @JsonProperty("mostUsedActivities")
    private BackendStatisticChart mostUsedActivities;

    @JsonProperty("activitiesPerUser")
    private BackendStatisticChart activitiesPerUser;

    @JsonProperty("userRegistrations")
    private BackendStatisticChart userRegistrations;


    public void setErrorsPerOperation(BackendStatisticChart errorsPerOperation) {
        this.errorsPerOperation = errorsPerOperation;
    }

    public BackendStatisticChart getErrorsPerOperation() {
        return this.errorsPerOperation;
    }

    public void setIncomingRequests(BackendStatisticChart incomingRequests) {
        this.incomingRequests = incomingRequests;
    }

    public BackendStatisticChart getIncomingRequests() {
        return this.incomingRequests;
    }

    public void setIncomingTransactions(BackendStatisticChart incomingTransactions) {
        this.incomingTransactions = incomingTransactions;
    }

    public BackendStatisticChart getIncomingTransactions() {
        return this.incomingTransactions;
    }

    public void setMostUsedOperations(BackendStatisticChart mostUsedOperations) {
        this.mostUsedOperations = mostUsedOperations;
    }

    public BackendStatisticChart getMostUsedOperations() {
        return this.mostUsedOperations;
    }

    public void setTimePerOperation(BackendStatisticChart timePerOperation) {
        this.timePerOperation = timePerOperation;
    }

    public BackendStatisticChart getTimePerOperation() {
        return this.timePerOperation;
    }

    public void setTestCoverage(BackendStatisticChart testCoverage) {
        this.testCoverage = testCoverage;
    }

    public BackendStatisticChart getTestCoverage() {
        return this.testCoverage;
    }

    public void setMostUsedActivities(BackendStatisticChart mostUsedActivities) {
        this.mostUsedActivities = mostUsedActivities;
    }

    public BackendStatisticChart getMostUsedActivities() {
        return this.mostUsedActivities;
    }

    public void setActivitiesPerUser(BackendStatisticChart activitiesPerUser) {
        this.activitiesPerUser = activitiesPerUser;
    }

    public BackendStatisticChart getActivitiesPerUser() {
        return this.activitiesPerUser;
    }

    public void setUserRegistrations(BackendStatisticChart userRegistrations) {
        this.userRegistrations = userRegistrations;
    }

    public BackendStatisticChart getUserRegistrations() {
        return this.userRegistrations;
    }
}

