/**
 * BackendSchemaForm automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import java.util.HashMap;

/**
 * Contains a UI vocabulary to describe the UI of the schema
 */
public class BackendSchemaForm extends HashMap<String, Object> {
}
