/**
 * BackendOperation automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("This object represents an operation, an operation invokes an action in case a specific HTTP method and path was requested. It defines also schema information about the request and response payload")
public class BackendOperation {
    @JsonPropertyDescription("Unique identifier for the object")
    @JsonProperty("id")
    private Integer id;

    @JsonPropertyDescription("Status of the object either 1 = active or 0 = deleted")
    @JsonProperty("status")
    private Integer status;

    @JsonPropertyDescription("Indicates whether the operation is active")
    @JsonProperty("active")
    private Boolean active;

    @JsonPropertyDescription("Indicates whether the operation is public, if false a user must provide an Authorization header with an Bearer access token")
    @JsonProperty("public")
    private Boolean _public;

    @JsonPropertyDescription("Describes the stability of this operation 0 = deprecated, 1 = experimental, 2 = stable and 3 = legacy")
    @JsonProperty("stability")
    private Integer stability;

    @JsonPropertyDescription("A short description of this operation, it should explain the operation in a simple and precise way")
    @JsonProperty("description")
    private String description;

    @JsonPropertyDescription("The target HTTP method i.e. GET or POST")
    @JsonProperty("httpMethod")
    private String httpMethod;

    @JsonPropertyDescription("The target HTTP path i.e. /foo or /product/:product_id")
    @JsonProperty("httpPath")
    private String httpPath;

    @JsonPropertyDescription("The success HTTP code i.e. 200 or 201")
    @JsonProperty("httpCode")
    private Integer httpCode;

    @JsonPropertyDescription("Unique name of the object. It is recommended to group your operations into logical units by using a dot i.e. product.getAll and product.insert which has also an effect on the automatically generated SDK")
    @JsonProperty("name")
    private String name;

    @JsonPropertyDescription("Describes available query parameters")
    @JsonProperty("parameters")
    private BackendOperationParameters parameters;

    @JsonPropertyDescription("Describes the incoming request payload, this must contain a schema name")
    @JsonProperty("incoming")
    private String incoming;

    @JsonPropertyDescription("Describes the outgoing response payload, this must contain a schema name")
    @JsonProperty("outgoing")
    private String outgoing;

    @JsonPropertyDescription("Describes error responses for i.e. client or server errors")
    @JsonProperty("throws")
    private BackendOperationThrows _throws;

    @JsonPropertyDescription("The target action to invoke, this must contain an action name")
    @JsonProperty("action")
    private String action;

    @JsonPropertyDescription("Costs to invoke this operation. A user can only invoke this operation in case he has enough points")
    @JsonProperty("costs")
    private Integer costs;

    @JsonPropertyDescription("Scopes which are required to invoke this operation")
    @JsonProperty("scopes")
    private java.util.List<String> scopes;

    @JsonPropertyDescription("Use this parameter to attach key-value data")
    @JsonProperty("metadata")
    private CommonMetadata metadata;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Boolean getActive() {
        return this.active;
    }

    public void setPublic(Boolean _public) {
        this._public = _public;
    }

    public Boolean getPublic() {
        return this._public;
    }

    public void setStability(Integer stability) {
        this.stability = stability;
    }

    public Integer getStability() {
        return this.stability;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return this.description;
    }

    public void setHttpMethod(String httpMethod) {
        this.httpMethod = httpMethod;
    }

    public String getHttpMethod() {
        return this.httpMethod;
    }

    public void setHttpPath(String httpPath) {
        this.httpPath = httpPath;
    }

    public String getHttpPath() {
        return this.httpPath;
    }

    public void setHttpCode(Integer httpCode) {
        this.httpCode = httpCode;
    }

    public Integer getHttpCode() {
        return this.httpCode;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setParameters(BackendOperationParameters parameters) {
        this.parameters = parameters;
    }

    public BackendOperationParameters getParameters() {
        return this.parameters;
    }

    public void setIncoming(String incoming) {
        this.incoming = incoming;
    }

    public String getIncoming() {
        return this.incoming;
    }

    public void setOutgoing(String outgoing) {
        this.outgoing = outgoing;
    }

    public String getOutgoing() {
        return this.outgoing;
    }

    public void setThrows(BackendOperationThrows _throws) {
        this._throws = _throws;
    }

    public BackendOperationThrows getThrows() {
        return this._throws;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public String getAction() {
        return this.action;
    }

    public void setCosts(Integer costs) {
        this.costs = costs;
    }

    public Integer getCosts() {
        return this.costs;
    }

    public void setScopes(java.util.List<String> scopes) {
        this.scopes = scopes;
    }

    public java.util.List<String> getScopes() {
        return this.scopes;
    }

    public void setMetadata(CommonMetadata metadata) {
        this.metadata = metadata;
    }

    public CommonMetadata getMetadata() {
        return this.metadata;
    }
}

