/**
 * CommonAgentContentText automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Text agent message")
public class CommonAgentContentText extends CommonAgentContent {
    @JsonPropertyDescription("The content text")
    private String content;

    @JsonSetter("content")
    public void setContent(String content) {
        this.content = content;
    }

    @JsonGetter("content")
    public String getContent() {
        return this.content;
    }
}

