/**
 * CommonFormElement automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class CommonFormElement {
    private String element;
    private String name;
    private String title;
    private String help;
    @JsonSetter("element")
    public void setElement(String element) {
        this.element = element;
    }
    @JsonGetter("element")
    public String getElement() {
        return this.element;
    }
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }
    @JsonGetter("name")
    public String getName() {
        return this.name;
    }
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }
    @JsonGetter("title")
    public String getTitle() {
        return this.title;
    }
    @JsonSetter("help")
    public void setHelp(String help) {
        this.help = help;
    }
    @JsonGetter("help")
    public String getHelp() {
        return this.help;
    }
}
