/**
 * CommonMetadata automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

public class CommonMetadata extends java.util.HashMap<String, String> {
}

