/**
 * ConsumerIdentityCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Collection of third-party identity providers")
public class ConsumerIdentityCollection extends CommonCollection<ConsumerIdentity> {
}

