/**
 * ConsumerForm automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Dynamic form configuration entity")
public class ConsumerForm {
    @JsonPropertyDescription("Uniquely identifies the object schema type")
    @JsonProperty("kind")
    private String kind;

    @JsonPropertyDescription("Unique identifier for the form")
    @JsonProperty("id")
    private Integer id;

    @JsonPropertyDescription("Name of the form")
    @JsonProperty("name")
    private String name;

    @JsonPropertyDescription("Target action path or route triggered on form submission")
    @JsonProperty("action")
    private String action;

    @JsonPropertyDescription("HTTP method used to submit the form (e.g., POST)")
    @JsonProperty("method")
    private String method;

    @JsonPropertyDescription("JSON Schema validating form structure and data inputs")
    @JsonProperty("jsonSchema")
    private Object jsonSchema;

    @JsonPropertyDescription("UI schema defining control layout and widget presentation options")
    @JsonProperty("uiSchema")
    private Object uiSchema;

    @JsonPropertyDescription("Custom metadata key-value mapping")
    @JsonProperty("metadata")
    private CommonMetadata metadata;


    public void setKind(String kind) {
        this.kind = kind;
    }

    public String getKind() {
        return this.kind;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public String getAction() {
        return this.action;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public String getMethod() {
        return this.method;
    }

    public void setJsonSchema(Object jsonSchema) {
        this.jsonSchema = jsonSchema;
    }

    public Object getJsonSchema() {
        return this.jsonSchema;
    }

    public void setUiSchema(Object uiSchema) {
        this.uiSchema = uiSchema;
    }

    public Object getUiSchema() {
        return this.uiSchema;
    }

    public void setMetadata(CommonMetadata metadata) {
        this.metadata = metadata;
    }

    public CommonMetadata getMetadata() {
        return this.metadata;
    }
}

