/**
 * ConsumerTokenUpdate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.time.LocalDate;
public class ConsumerTokenUpdate {
    private String name;
    private LocalDate expire;
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }
    @JsonGetter("name")
    public String getName() {
        return this.name;
    }
    @JsonSetter("expire")
    public void setExpire(LocalDate expire) {
        this.expire = expire;
    }
    @JsonGetter("expire")
    public LocalDate getExpire() {
        return this.expire;
    }
}
