/**
 * ConsumerPlanCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Collection of subscription plans")
public class ConsumerPlanCollection extends CommonCollection<ConsumerPlan> {
}

