/**
 * ConsumerAgent automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("This object represents an agent")
public class ConsumerAgent {
    @JsonPropertyDescription("Unique identifier for the object")
    @JsonProperty("id")
    private Integer id;

    @JsonPropertyDescription("Name of the agent")
    @JsonProperty("name")
    private String name;

    @JsonPropertyDescription("Description of the agent")
    @JsonProperty("description")
    private String description;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return this.description;
    }
}

