/**
 * ConsumerPaymentPortalRequest automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ConsumerPaymentPortalRequest {
    private String returnUrl;

    @JsonSetter("returnUrl")
    public void setReturnUrl(String returnUrl) {
        this.returnUrl = returnUrl;
    }

    @JsonGetter("returnUrl")
    public String getReturnUrl() {
        return this.returnUrl;
    }
}

