/**
 * ConsumerPaymentCheckoutRequest automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Request payload to initiate a checkout flow for a plan")
public class ConsumerPaymentCheckoutRequest {
    @JsonPropertyDescription("Target subscription plan ID to purchase")
    @JsonProperty("planId")
    private Integer planId;

    @JsonPropertyDescription("URL where the user is redirected after successful payment completion")
    @JsonProperty("returnUrl")
    private String returnUrl;


    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    public Integer getPlanId() {
        return this.planId;
    }

    public void setReturnUrl(String returnUrl) {
        this.returnUrl = returnUrl;
    }

    public String getReturnUrl() {
        return this.returnUrl;
    }
}

