/**
 * ConsumerUserPlan automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Active plan summary associated with a user")
public class ConsumerUserPlan {
    @JsonPropertyDescription("Unique identifier for the assigned plan")
    @JsonProperty("id")
    private Integer id;

    @JsonPropertyDescription("Name of the assigned plan")
    @JsonProperty("name")
    private String name;

    @JsonPropertyDescription("Price of the plan")
    @JsonProperty("price")
    private Integer price;

    @JsonPropertyDescription("Points granted by the plan")
    @JsonProperty("points")
    private Integer points;

    @JsonPropertyDescription("Billing period interval classification code")
    @JsonProperty("period")
    private Integer period;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public Integer getPrice() {
        return this.price;
    }

    public void setPoints(Integer points) {
        this.points = points;
    }

    public Integer getPoints() {
        return this.points;
    }

    public void setPeriod(Integer period) {
        this.period = period;
    }

    public Integer getPeriod() {
        return this.period;
    }
}

