/**
 * ConsumerWebhook automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

public class ConsumerWebhook {
    @JsonProperty("id")
    private Integer id;

    @JsonProperty("status")
    private Integer status;

    @JsonProperty("event")
    private String event;

    @JsonProperty("name")
    private String name;

    @JsonProperty("endpoint")
    private String endpoint;

    @JsonProperty("responses")
    private java.util.List<ConsumerWebhookResponse> responses;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setEvent(String event) {
        this.event = event;
    }

    public String getEvent() {
        return this.event;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }

    public String getEndpoint() {
        return this.endpoint;
    }

    public void setResponses(java.util.List<ConsumerWebhookResponse> responses) {
        this.responses = responses;
    }

    public java.util.List<ConsumerWebhookResponse> getResponses() {
        return this.responses;
    }
}

