/**
 * ConsumerGrantCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Collection of user authorization grant records")
public class ConsumerGrantCollection extends CommonCollection<ConsumerGrant> {
}

