/**
 * ConsumerPageCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Collection of content page entries")
public class ConsumerPageCollection extends CommonCollection<ConsumerPage> {
}

