/**
 * ConsumerApp automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

public class ConsumerApp {
    @JsonProperty("id")
    private Integer id;

    @JsonProperty("userId")
    private Integer userId;

    @JsonProperty("status")
    private Integer status;

    @JsonProperty("name")
    private String name;

    @JsonProperty("url")
    private String url;

    @JsonProperty("appKey")
    private String appKey;

    @JsonProperty("appSecret")
    private String appSecret;

    @JsonProperty("date")
    private String date;

    @JsonProperty("scopes")
    private java.util.List<String> scopes;

    @JsonProperty("metadata")
    private CommonMetadata metadata;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getUrl() {
        return this.url;
    }

    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }

    public String getAppKey() {
        return this.appKey;
    }

    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret;
    }

    public String getAppSecret() {
        return this.appSecret;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getDate() {
        return this.date;
    }

    public void setScopes(java.util.List<String> scopes) {
        this.scopes = scopes;
    }

    public java.util.List<String> getScopes() {
        return this.scopes;
    }

    public void setMetadata(CommonMetadata metadata) {
        this.metadata = metadata;
    }

    public CommonMetadata getMetadata() {
        return this.metadata;
    }
}

