/**
 * MarketplaceMessageException automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import app.sdkgen.client.Exception.KnownStatusCodeException;

public class MarketplaceMessageException extends KnownStatusCodeException {

    private MarketplaceMessage payload;

    public MarketplaceMessageException(MarketplaceMessage payload) {
        super("The server returned an error");

        this.payload = payload;
    }

    public MarketplaceMessage getPayload() {
        return this.payload;
    }

}
