/**
 * MarketplaceBundleConfig automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

public class MarketplaceBundleConfig {
    @JsonProperty("actions")
    private java.util.List<MarketplaceBundleAction> actions;

    @JsonProperty("schemas")
    private java.util.List<MarketplaceBundleSchema> schemas;

    @JsonProperty("events")
    private java.util.List<MarketplaceBundleEvent> events;

    @JsonProperty("cronjobs")
    private java.util.List<MarketplaceBundleCronjob> cronjobs;

    @JsonProperty("triggers")
    private java.util.List<MarketplaceBundleTrigger> triggers;


    public void setActions(java.util.List<MarketplaceBundleAction> actions) {
        this.actions = actions;
    }

    public java.util.List<MarketplaceBundleAction> getActions() {
        return this.actions;
    }

    public void setSchemas(java.util.List<MarketplaceBundleSchema> schemas) {
        this.schemas = schemas;
    }

    public java.util.List<MarketplaceBundleSchema> getSchemas() {
        return this.schemas;
    }

    public void setEvents(java.util.List<MarketplaceBundleEvent> events) {
        this.events = events;
    }

    public java.util.List<MarketplaceBundleEvent> getEvents() {
        return this.events;
    }

    public void setCronjobs(java.util.List<MarketplaceBundleCronjob> cronjobs) {
        this.cronjobs = cronjobs;
    }

    public java.util.List<MarketplaceBundleCronjob> getCronjobs() {
        return this.cronjobs;
    }

    public void setTriggers(java.util.List<MarketplaceBundleTrigger> triggers) {
        this.triggers = triggers;
    }

    public java.util.List<MarketplaceBundleTrigger> getTriggers() {
        return this.triggers;
    }
}

