/**
 * MarketplaceApp automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

public class MarketplaceApp extends MarketplaceObject {
    @JsonProperty("scopes")
    private java.util.List<String> scopes;

    @JsonProperty("downloadUrl")
    private String downloadUrl;

    @JsonProperty("hash")
    private String hash;


    public void setScopes(java.util.List<String> scopes) {
        this.scopes = scopes;
    }

    public java.util.List<String> getScopes() {
        return this.scopes;
    }

    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl;
    }

    public String getDownloadUrl() {
        return this.downloadUrl;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public String getHash() {
        return this.hash;
    }
}

