/**
 * MarketplaceCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class MarketplaceCollection<T> {
    private Integer totalResults;
    private Integer startIndex;
    private Integer itemsPerPage;
    private List<T> entry;
    @JsonSetter("totalResults")
    public void setTotalResults(Integer totalResults) {
        this.totalResults = totalResults;
    }
    @JsonGetter("totalResults")
    public Integer getTotalResults() {
        return this.totalResults;
    }
    @JsonSetter("startIndex")
    public void setStartIndex(Integer startIndex) {
        this.startIndex = startIndex;
    }
    @JsonGetter("startIndex")
    public Integer getStartIndex() {
        return this.startIndex;
    }
    @JsonSetter("itemsPerPage")
    public void setItemsPerPage(Integer itemsPerPage) {
        this.itemsPerPage = itemsPerPage;
    }
    @JsonGetter("itemsPerPage")
    public Integer getItemsPerPage() {
        return this.itemsPerPage;
    }
    @JsonSetter("entry")
    public void setEntry(List<T> entry) {
        this.entry = entry;
    }
    @JsonGetter("entry")
    public List<T> getEntry() {
        return this.entry;
    }
}
