/**
 * MarketplaceObject automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Base class of all objects on the marketplace")
public class MarketplaceObject {
    @JsonProperty("id")
    private Integer id;

    @JsonProperty("name")
    private String name;

    @JsonProperty("author")
    private MarketplaceUser author;

    @JsonProperty("version")
    private String version;

    @JsonProperty("icon")
    private String icon;

    @JsonProperty("summary")
    private String summary;

    @JsonProperty("description")
    private String description;

    @JsonProperty("cost")
    private Integer cost;

    @JsonProperty("updateDate")
    private java.time.LocalDateTime updateDate;

    @JsonProperty("insertDate")
    private java.time.LocalDateTime insertDate;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setAuthor(MarketplaceUser author) {
        this.author = author;
    }

    public MarketplaceUser getAuthor() {
        return this.author;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getVersion() {
        return this.version;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getIcon() {
        return this.icon;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getSummary() {
        return this.summary;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return this.description;
    }

    public void setCost(Integer cost) {
        this.cost = cost;
    }

    public Integer getCost() {
        return this.cost;
    }

    public void setUpdateDate(java.time.LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    public java.time.LocalDateTime getUpdateDate() {
        return this.updateDate;
    }

    public void setInsertDate(java.time.LocalDateTime insertDate) {
        this.insertDate = insertDate;
    }

    public java.time.LocalDateTime getInsertDate() {
        return this.insertDate;
    }
}

