/**
 * MarketplaceBundle automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

public class MarketplaceBundle extends MarketplaceObject {
    @JsonProperty("config")
    private MarketplaceBundleConfig config;


    public void setConfig(MarketplaceBundleConfig config) {
        this.config = config;
    }

    public MarketplaceBundleConfig getConfig() {
        return this.config;
    }
}

