/**
 * MarketplaceBundleActionConfig automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

public class MarketplaceBundleActionConfig extends java.util.HashMap<String, Object> {
}

