/**
 * Passthru automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import java.util.HashMap;

/**
 * No schema information available
 */
public class Passthru extends HashMap<String, Object> {
}
