/**
 * SystemAbout automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

public class SystemAbout {
    @JsonProperty("apiVersion")
    private String apiVersion;

    @JsonProperty("title")
    private String title;

    @JsonProperty("description")
    private String description;

    @JsonProperty("termsOfService")
    private String termsOfService;

    @JsonProperty("contactName")
    private String contactName;

    @JsonProperty("contactUrl")
    private String contactUrl;

    @JsonProperty("contactEmail")
    private String contactEmail;

    @JsonProperty("licenseName")
    private String licenseName;

    @JsonProperty("licenseUrl")
    private String licenseUrl;

    @JsonProperty("paymentCurrency")
    private String paymentCurrency;

    @JsonProperty("categories")
    private java.util.List<String> categories;

    @JsonProperty("scopes")
    private java.util.List<String> scopes;

    @JsonProperty("apps")
    private SystemAboutApps apps;

    @JsonProperty("links")
    private java.util.List<SystemAboutLink> links;


    public void setApiVersion(String apiVersion) {
        this.apiVersion = apiVersion;
    }

    public String getApiVersion() {
        return this.apiVersion;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitle() {
        return this.title;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return this.description;
    }

    public void setTermsOfService(String termsOfService) {
        this.termsOfService = termsOfService;
    }

    public String getTermsOfService() {
        return this.termsOfService;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public String getContactName() {
        return this.contactName;
    }

    public void setContactUrl(String contactUrl) {
        this.contactUrl = contactUrl;
    }

    public String getContactUrl() {
        return this.contactUrl;
    }

    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    public String getContactEmail() {
        return this.contactEmail;
    }

    public void setLicenseName(String licenseName) {
        this.licenseName = licenseName;
    }

    public String getLicenseName() {
        return this.licenseName;
    }

    public void setLicenseUrl(String licenseUrl) {
        this.licenseUrl = licenseUrl;
    }

    public String getLicenseUrl() {
        return this.licenseUrl;
    }

    public void setPaymentCurrency(String paymentCurrency) {
        this.paymentCurrency = paymentCurrency;
    }

    public String getPaymentCurrency() {
        return this.paymentCurrency;
    }

    public void setCategories(java.util.List<String> categories) {
        this.categories = categories;
    }

    public java.util.List<String> getCategories() {
        return this.categories;
    }

    public void setScopes(java.util.List<String> scopes) {
        this.scopes = scopes;
    }

    public java.util.List<String> getScopes() {
        return this.scopes;
    }

    public void setApps(SystemAboutApps apps) {
        this.apps = apps;
    }

    public SystemAboutApps getApps() {
        return this.apps;
    }

    public void setLinks(java.util.List<SystemAboutLink> links) {
        this.links = links;
    }

    public java.util.List<SystemAboutLink> getLinks() {
        return this.links;
    }
}

