/**
 * SystemCaptchaChallenge automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import com.fasterxml.jackson.annotation.*;

public class SystemCaptchaChallenge {
    @JsonPropertyDescription("Cryptographic algorithm used to generate the proof-of-work/CAPTCHA challenge")
    @JsonProperty("algorithm")
    private String algorithm;

    @JsonPropertyDescription("Unique challenge string to be solved or signed by the client")
    @JsonProperty("challenge")
    private String challenge;

    @JsonPropertyDescription("Maximum integer bound used for the proof-of-work search space")
    @JsonProperty("maxnumber")
    private Integer maxnumber;

    @JsonPropertyDescription("Random salt appended to the challenge string during verification")
    @JsonProperty("salt")
    private String salt;

    @JsonPropertyDescription("Server-generated signature validating the authenticity of the challenge")
    @JsonProperty("signature")
    private String signature;

    @JsonPropertyDescription("Unix timestamp indicating when the CAPTCHA challenge becomes invalid")
    @JsonProperty("expires")
    private Integer expires;


    public void setAlgorithm(String algorithm) {
        this.algorithm = algorithm;
    }

    public String getAlgorithm() {
        return this.algorithm;
    }

    public void setChallenge(String challenge) {
        this.challenge = challenge;
    }

    public String getChallenge() {
        return this.challenge;
    }

    public void setMaxnumber(Integer maxnumber) {
        this.maxnumber = maxnumber;
    }

    public Integer getMaxnumber() {
        return this.maxnumber;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public String getSalt() {
        return this.salt;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    public String getSignature() {
        return this.signature;
    }

    public void setExpires(Integer expires) {
        this.expires = expires;
    }

    public Integer getExpires() {
        return this.expires;
    }
}

