/**
 * SystemTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk;

import app.sdkgen.client.Exception.ClientException;
import app.sdkgen.client.Exception.UnknownStatusCodeException;
import app.sdkgen.client.Parser;
import app.sdkgen.client.TagAbstract;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.*;
import org.apache.http.client.utils.URIBuilder;
import org.apache.http.entity.ContentType;
import org.apache.http.entity.StringEntity;
import org.apache.http.util.EntityUtils;

import java.io.IOException;
import java.net.URISyntaxException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

public class SystemTag extends TagAbstract {
    public SystemTag(HttpClient httpClient, ObjectMapper objectMapper, Parser parser) {
        super(httpClient, objectMapper, parser);
    }

    public SystemPaymentTag payment()
    {
        return new SystemPaymentTag(
            this.httpClient,
            this.objectMapper,
            this.parser
        );
    }

    public SystemMetaTag meta()
    {
        return new SystemMetaTag(
            this.httpClient,
            this.objectMapper,
            this.parser
        );
    }

    public SystemConnectionTag connection()
    {
        return new SystemConnectionTag(
            this.httpClient,
            this.objectMapper,
            this.parser
        );
    }


}
