/**
 * Action automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class Action {
    private int id;
    private int status;
    private String name;
    private String _class;
    private boolean async;
    private String engine;
    private Action_Config config;
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }
    @JsonGetter("id")
    public int getId() {
        return this.id;
    }
    @JsonSetter("status")
    public void setStatus(int status) {
        this.status = status;
    }
    @JsonGetter("status")
    public int getStatus() {
        return this.status;
    }
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }
    @JsonGetter("name")
    public String getName() {
        return this.name;
    }
    @JsonSetter("class")
    public void set_Class(String _class) {
        this._class = _class;
    }
    @JsonGetter("class")
    public String get_Class() {
        return this._class;
    }
    @JsonSetter("async")
    public void setAsync(boolean async) {
        this.async = async;
    }
    @JsonGetter("async")
    public boolean getAsync() {
        return this.async;
    }
    @JsonSetter("engine")
    public void setEngine(String engine) {
        this.engine = engine;
    }
    @JsonGetter("engine")
    public String getEngine() {
        return this.engine;
    }
    @JsonSetter("config")
    public void setConfig(Action_Config config) {
        this.config = config;
    }
    @JsonGetter("config")
    public Action_Config getConfig() {
        return this.config;
    }
}
