/**
 * BackendAppApp_idTokenToken_idPath automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class BackendAppApp_idTokenToken_idPath {
    private String app_id;
    private String token_id;
    @JsonSetter("app_id")
    public void setApp_id(String app_id) {
        this.app_id = app_id;
    }
    @JsonGetter("app_id")
    public String getApp_id() {
        return this.app_id;
    }
    @JsonSetter("token_id")
    public void setToken_id(String token_id) {
        this.token_id = token_id;
    }
    @JsonGetter("token_id")
    public String getToken_id() {
        return this.token_id;
    }
}
