/**
 * BackendRateGroup automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import app.sdkgen.client.ResourceAbstract;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.http.client.HttpClient;

public class BackendRateGroup extends ResourceAbstract {
    public BackendRateGroup(String baseUrl, HttpClient httpClient, ObjectMapper objectMapper) {
        super(baseUrl, httpClient, objectMapper);
    }

    /**
     * Endpoint: /backend/rate/$rate_id<[0-9]+|^~>
     */
    public BackendRateByRateIdResource getBackendRateByRateId(String rate_id) {
        return new BackendRateByRateIdResource(
            rate_id,
            this.baseUrl,
            this.httpClient
        );
    }

    /**
     * Endpoint: /backend/rate
     */
    public BackendRateResource getBackendRate() {
        return new BackendRateResource(
            this.baseUrl,
            this.httpClient
        );
    }

}
