/**
 * Backend_Plan_Usage_Collection_Query automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class Backend_Plan_Usage_Collection_Query extends Plan_Usage_Collection_Query {
}
