/**
 * BackendLogErrorError_idPath automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class BackendLogErrorError_idPath {
    private String error_id;
    @JsonSetter("error_id")
    public void setError_id(String error_id) {
        this.error_id = error_id;
    }
    @JsonGetter("error_id")
    public String getError_id() {
        return this.error_id;
    }
}
