/**
 * BackendTrashGroup automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import app.sdkgen.client.ResourceAbstract;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.http.client.HttpClient;

public class BackendTrashGroup extends ResourceAbstract {
    public BackendTrashGroup(String baseUrl, HttpClient httpClient, ObjectMapper objectMapper) {
        super(baseUrl, httpClient, objectMapper);
    }

    /**
     * Endpoint: /backend/trash/:type
     */
    public BackendTrashByTypeResource getBackendTrashByType(String type) {
        return new BackendTrashByTypeResource(
            type,
            this.baseUrl,
            this.httpClient
        );
    }

    /**
     * Endpoint: /backend/trash
     */
    public BackendTrashResource getBackendTrash() {
        return new BackendTrashResource(
            this.baseUrl,
            this.httpClient
        );
    }

}
