/**
 * BackendScopeGroup automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import app.sdkgen.client.ResourceAbstract;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.http.client.HttpClient;

public class BackendScopeGroup extends ResourceAbstract {
    public BackendScopeGroup(String baseUrl, HttpClient httpClient, ObjectMapper objectMapper) {
        super(baseUrl, httpClient, objectMapper);
    }

    /**
     * Endpoint: /backend/scope/$scope_id<[0-9]+|^~>
     */
    public BackendScopeByScopeIdResource getBackendScopeByScopeId(String scope_id) {
        return new BackendScopeByScopeIdResource(
            scope_id,
            this.baseUrl,
            this.httpClient
        );
    }

    /**
     * Endpoint: /backend/scope/categories
     */
    public BackendScopeCategoriesResource getBackendScopeCategories() {
        return new BackendScopeCategoriesResource(
            this.baseUrl,
            this.httpClient
        );
    }

    /**
     * Endpoint: /backend/scope
     */
    public BackendScopeResource getBackendScope() {
        return new BackendScopeResource(
            this.baseUrl,
            this.httpClient
        );
    }

}
