/**
 * BackendAppAppIdPath automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class BackendAppAppIdPath {
    private String appId;
    @JsonSetter("app_id")
    public void setAppId(String appId) {
        this.appId = appId;
    }
    @JsonGetter("app_id")
    public String getAppId() {
        return this.appId;
    }
}
