/**
 * BackendPagePage_idPath automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class BackendPagePage_idPath {
    private String page_id;
    @JsonSetter("page_id")
    public void setPage_id(String page_id) {
        this.page_id = page_id;
    }
    @JsonGetter("page_id")
    public String getPage_id() {
        return this.page_id;
    }
}
