/**
 * BackendAppByAppIdTokenAndTokenIdResource automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import app.sdkgen.client.ResourceAbstract;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.*;
import org.apache.http.client.utils.URIBuilder;
import org.apache.http.entity.ContentType;
import org.apache.http.entity.StringEntity;
import org.apache.http.util.EntityUtils;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.Map;

public class BackendAppByAppIdTokenAndTokenIdResource extends ResourceAbstract {
    private final String url;
    private final HttpClient httpClient;
    private final ObjectMapper objectMapper;

    private final String appId;
    private final String tokenId;

    public BackendAppByAppIdTokenAndTokenIdResource(String appId, String tokenId, String baseUrl, HttpClient httpClient, ObjectMapper objectMapper) {
        super(baseUrl, httpClient, objectMapper);

        this.appId = appId;
        this.tokenId = tokenId;

        this.url = baseUrl + "/backend/app/"+appId+"/token/"+tokenId+"";
        this.httpClient = httpClient;
        this.objectMapper = objectMapper;
    }

    public BackendAppByAppIdTokenAndTokenIdResource(String appId, String tokenId, String baseUrl, HttpClient httpClient) {
        this(appId, tokenId, baseUrl, httpClient, new ObjectMapper());
    }

    public Message backendActionAppDeleteToken() throws URISyntaxException, IOException {
        URIBuilder builder = new URIBuilder(this.url);


        HttpDelete request = new HttpDelete(builder.build());

        HttpResponse response = this.httpClient.execute(request);

        return this.objectMapper.readValue(EntityUtils.toString(response.getEntity(), "UTF-8"), Message.class);
    }

}
