/**
 * BackendConnectionConnectionIdRedirectPath automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class BackendConnectionConnectionIdRedirectPath {
    private String connectionId;
    @JsonSetter("connection_id")
    public void setConnectionId(String connectionId) {
        this.connectionId = connectionId;
    }
    @JsonGetter("connection_id")
    public String getConnectionId() {
        return this.connectionId;
    }
}
