/**
 * BackendStatisticGroup automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import app.sdkgen.client.ResourceAbstract;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.http.client.HttpClient;

public class BackendStatisticGroup extends ResourceAbstract {
    public BackendStatisticGroup(String baseUrl, HttpClient httpClient, ObjectMapper objectMapper) {
        super(baseUrl, httpClient, objectMapper);
    }

    /**
     * Endpoint: /backend/statistic/used_points
     */
    public BackendStatisticUsedPointsResource getBackendStatisticUsedPoints() {
        return new BackendStatisticUsedPointsResource(
            this.baseUrl,
            this.httpClient
        );
    }

    /**
     * Endpoint: /backend/statistic/time_per_route
     */
    public BackendStatisticTimePerRouteResource getBackendStatisticTimePerRoute() {
        return new BackendStatisticTimePerRouteResource(
            this.baseUrl,
            this.httpClient
        );
    }

    /**
     * Endpoint: /backend/statistic/time_average
     */
    public BackendStatisticTimeAverageResource getBackendStatisticTimeAverage() {
        return new BackendStatisticTimeAverageResource(
            this.baseUrl,
            this.httpClient
        );
    }

    /**
     * Endpoint: /backend/statistic/most_used_routes
     */
    public BackendStatisticMostUsedRoutesResource getBackendStatisticMostUsedRoutes() {
        return new BackendStatisticMostUsedRoutesResource(
            this.baseUrl,
            this.httpClient
        );
    }

    /**
     * Endpoint: /backend/statistic/most_used_apps
     */
    public BackendStatisticMostUsedAppsResource getBackendStatisticMostUsedApps() {
        return new BackendStatisticMostUsedAppsResource(
            this.baseUrl,
            this.httpClient
        );
    }

    /**
     * Endpoint: /backend/statistic/issued_tokens
     */
    public BackendStatisticIssuedTokensResource getBackendStatisticIssuedTokens() {
        return new BackendStatisticIssuedTokensResource(
            this.baseUrl,
            this.httpClient
        );
    }

    /**
     * Endpoint: /backend/statistic/incoming_transactions
     */
    public BackendStatisticIncomingTransactionsResource getBackendStatisticIncomingTransactions() {
        return new BackendStatisticIncomingTransactionsResource(
            this.baseUrl,
            this.httpClient
        );
    }

    /**
     * Endpoint: /backend/statistic/incoming_requests
     */
    public BackendStatisticIncomingRequestsResource getBackendStatisticIncomingRequests() {
        return new BackendStatisticIncomingRequestsResource(
            this.baseUrl,
            this.httpClient
        );
    }

    /**
     * Endpoint: /backend/statistic/errors_per_route
     */
    public BackendStatisticErrorsPerRouteResource getBackendStatisticErrorsPerRoute() {
        return new BackendStatisticErrorsPerRouteResource(
            this.baseUrl,
            this.httpClient
        );
    }

    /**
     * Endpoint: /backend/statistic/count_requests
     */
    public BackendStatisticCountRequestsResource getBackendStatisticCountRequests() {
        return new BackendStatisticCountRequestsResource(
            this.baseUrl,
            this.httpClient
        );
    }

}
