/**
 * Collection_Category_Query automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class Collection_Category_Query extends Collection_Query {
    private int categoryId;
    @JsonSetter("categoryId")
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }
    @JsonGetter("categoryId")
    public int getCategoryId() {
        return this.categoryId;
    }
}
