/**
 * Connection_Introspection_Entity automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class Connection_Introspection_Entity {
    private String name;
    private String[] headers;
    private Connection_Introspection_Entity_Row[] rows;
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }
    @JsonGetter("name")
    public String getName() {
        return this.name;
    }
    @JsonSetter("headers")
    public void setHeaders(String[] headers) {
        this.headers = headers;
    }
    @JsonGetter("headers")
    public String[] getHeaders() {
        return this.headers;
    }
    @JsonSetter("rows")
    public void setRows(Connection_Introspection_Entity_Row[] rows) {
        this.rows = rows;
    }
    @JsonGetter("rows")
    public Connection_Introspection_Entity_Row[] getRows() {
        return this.rows;
    }
}
