/**
 * DashboardTransaction automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.time.LocalDateTime;
public class DashboardTransaction {
    private int id;
    private String status;
    private String provider;
    private String transactionId;
    private float amount;
    private LocalDateTime date;
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }
    @JsonGetter("id")
    public int getId() {
        return this.id;
    }
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }
    @JsonGetter("status")
    public String getStatus() {
        return this.status;
    }
    @JsonSetter("provider")
    public void setProvider(String provider) {
        this.provider = provider;
    }
    @JsonGetter("provider")
    public String getProvider() {
        return this.provider;
    }
    @JsonSetter("transactionId")
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }
    @JsonGetter("transactionId")
    public String getTransactionId() {
        return this.transactionId;
    }
    @JsonSetter("amount")
    public void setAmount(float amount) {
        this.amount = amount;
    }
    @JsonGetter("amount")
    public float getAmount() {
        return this.amount;
    }
    @JsonSetter("date")
    public void setDate(LocalDateTime date) {
        this.date = date;
    }
    @JsonGetter("date")
    public LocalDateTime getDate() {
        return this.date;
    }
}
