/**
 * FormElementTextArea automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class FormElementTextArea extends FormElement {
    private String mode;
    @JsonSetter("mode")
    public void setMode(String mode) {
        this.mode = mode;
    }
    @JsonGetter("mode")
    public String getMode() {
        return this.mode;
    }
}
