/**
 * Generator_Index_Providers automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class Generator_Index_Providers {
    private Generator_Index_Provider[] providers;
    @JsonSetter("providers")
    public void setProviders(Generator_Index_Provider[] providers) {
        this.providers = providers;
    }
    @JsonGetter("providers")
    public Generator_Index_Provider[] getProviders() {
        return this.providers;
    }
}
