/**
 * GeneratorProviderChangelog automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class GeneratorProviderChangelog {
    private Schema[] schemas;
    private Action[] actions;
    private Route[] routes;
    @JsonSetter("schemas")
    public void setSchemas(Schema[] schemas) {
        this.schemas = schemas;
    }
    @JsonGetter("schemas")
    public Schema[] getSchemas() {
        return this.schemas;
    }
    @JsonSetter("actions")
    public void setActions(Action[] actions) {
        this.actions = actions;
    }
    @JsonGetter("actions")
    public Action[] getActions() {
        return this.actions;
    }
    @JsonSetter("routes")
    public void setRoutes(Route[] routes) {
        this.routes = routes;
    }
    @JsonGetter("routes")
    public Route[] getRoutes() {
        return this.routes;
    }
}
