/**
 * Log_Collection_Query automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.time.LocalDateTime;
public class Log_Collection_Query extends Collection_Query {
    private LocalDateTime from;
    private LocalDateTime to;
    private int routeId;
    private int appId;
    private int userId;
    private String ip;
    private String userAgent;
    private String method;
    private String path;
    private String header;
    private String body;
    private String search;
    @JsonSetter("from")
    public void setFrom(LocalDateTime from) {
        this.from = from;
    }
    @JsonGetter("from")
    public LocalDateTime getFrom() {
        return this.from;
    }
    @JsonSetter("to")
    public void setTo(LocalDateTime to) {
        this.to = to;
    }
    @JsonGetter("to")
    public LocalDateTime getTo() {
        return this.to;
    }
    @JsonSetter("routeId")
    public void setRouteId(int routeId) {
        this.routeId = routeId;
    }
    @JsonGetter("routeId")
    public int getRouteId() {
        return this.routeId;
    }
    @JsonSetter("appId")
    public void setAppId(int appId) {
        this.appId = appId;
    }
    @JsonGetter("appId")
    public int getAppId() {
        return this.appId;
    }
    @JsonSetter("userId")
    public void setUserId(int userId) {
        this.userId = userId;
    }
    @JsonGetter("userId")
    public int getUserId() {
        return this.userId;
    }
    @JsonSetter("ip")
    public void setIp(String ip) {
        this.ip = ip;
    }
    @JsonGetter("ip")
    public String getIp() {
        return this.ip;
    }
    @JsonSetter("userAgent")
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }
    @JsonGetter("userAgent")
    public String getUserAgent() {
        return this.userAgent;
    }
    @JsonSetter("method")
    public void setMethod(String method) {
        this.method = method;
    }
    @JsonGetter("method")
    public String getMethod() {
        return this.method;
    }
    @JsonSetter("path")
    public void setPath(String path) {
        this.path = path;
    }
    @JsonGetter("path")
    public String getPath() {
        return this.path;
    }
    @JsonSetter("header")
    public void setHeader(String header) {
        this.header = header;
    }
    @JsonGetter("header")
    public String getHeader() {
        return this.header;
    }
    @JsonSetter("body")
    public void setBody(String body) {
        this.body = body;
    }
    @JsonGetter("body")
    public String getBody() {
        return this.body;
    }
    @JsonSetter("search")
    public void setSearch(String search) {
        this.search = search;
    }
    @JsonGetter("search")
    public String getSearch() {
        return this.search;
    }
}
