/**
 * Marketplace_Collection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class Marketplace_Collection {
    private Marketplace_Collection_Apps apps;
    @JsonSetter("apps")
    public void setApps(Marketplace_Collection_Apps apps) {
        this.apps = apps;
    }
    @JsonGetter("apps")
    public Marketplace_Collection_Apps getApps() {
        return this.apps;
    }
}
