/**
 * Sdk_Response automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.fusioproject.sdk.backend;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class Sdk_Response {
    private Sdk_Types types;
    @JsonSetter("types")
    public void setTypes(Sdk_Types types) {
        this.types = types;
    }
    @JsonGetter("types")
    public Sdk_Types getTypes() {
        return this.types;
    }
}
